local dirPath = rootDir() .. "/Facebook/images_vn/"

what_is_birthday = {dirPath .. "what_is_your_birthday2.png"}
next = {dirPath .. "next.png", dirPath .. "next2.png", dirPath .. "next3.png", dirPath .. "next4.png"}
what_is_gender = {dirPath .. "what_is_your_gender.png"}
what_is_mobile_number = {dirPath .. "what_is_your_phone2.png"}
sign_up_with_email = {dirPath .. "sign_up_with_email.png"}
what_is_your_email = {dirPath .. "what_is_your_email.png"}
continue_creating_account = {dirPath .. "continue_create_account3.png"}
save = {dirPath .. "save.png", dirPath .. "save7.png", dirPath .. "save6.png"}
save_your_login_info = {dirPath .. "save_your_login_info2.png"}
enter_the_confirmation_code = {dirPath .. "enter_the_confirmation_code.png", dirPath .. "enter_the_confirmation_code2.png"}
profile_picture = {dirPath .. "profile_picture.png", dirPath .. "add_picture.png", dirPath .. "profile_picture5.png", 
    dirPath .. "profile_picture6.png", dirPath .. "profile_picture7.png"}
turn_on_contact = {dirPath .. "turn_on_contact7.png", dirPath .. "turn_on_contact8.png", dirPath .. "turn_on_contact9.png"}
skip = {dirPath .. "skip.png", dirPath .. "skip2.png", dirPath .. "skip3.png", 
    dirPath .. "skip4.png", dirPath .. "skip5.png", dirPath .. "skip6.png"}
not_now = {dirPath .. "not_now.png", dirPath .. "not_now7.png", dirPath .. "not_now8.png", dirPath .. "not_now9.png"}
no_friend = {dirPath .. "no_friend.png", dirPath .. "no_friend4.png", dirPath .. "contact_icon.png"}
find_friend = {dirPath .. "find_friend3.png"}
what_on_your_mind = {dirPath .. "what_on_your_mind.png"}

create_new_account = {dirPath .. "create_new_acc7.png", dirPath .. "create_new_acc.png", dirPath .. "create_new_acc2.png", 
    dirPath .. "create_new_acc3.png", dirPath .. "create_new_acc5.png", dirPath .. "create_new_acc6.png", dirPath .. "create_new_acc8.png"}
create_new_account_blue = {dirPath .. "create_new_acc_blue.png"}
get_started = {dirPath .. "get_started2.png"}
what_name = {dirPath .. "what_name.png"}
already_have_account = {dirPath .. "do_you_already_have_account2.png"}
setting_menu = {dirPath .. "setting_menu3.png", dirPath .. "setting_menu2.png", dirPath .. "setting_menu.png"}
setting_privacy = {dirPath .. "setting_privacy.png", dirPath .. "search_setting.png"}
see_more_account_center = {dirPath .. "see_more_account_center.png"}
account_center = {dirPath .. "account_center.png"}
personal_details_btn = {dirPath .. "personal_details_btn.png", dirPath .. "personal_details_btn2.png"}
personal_details_page = {dirPath .. "personal_details_page.png"}
your_information_and_permission = {dirPath .. "your_information_and_permission.png"}
your_information_and_per_btn = {dirPath .. "your_information_and_per_btn2.png"}
identify_confirmation_btn = {dirPath .. "identify_confirmation_btn.png"}
confirm_your_identity = {dirPath .. "confirm_your_identity.png"}
protect_your_account = {dirPath .. "protect_your_account.png"}
reenter_password = {dirPath .. "reenter_password.png"}
input_password = {dirPath .. "input_password.png", dirPath .. "input_password2.png"}
help_protect_account = {dirPath .. "help_protect_account.png"}
instructions_for_setup = {dirPath .. "instructions_for_setup.png"}
copy_key = {dirPath .. "copy_key.png"}
two_FA_code = {dirPath .. "two_FA_code.png"}
two_factor_is_on = {dirPath .. "two_factor_is_on.png"}
logout_btn = {dirPath .. "logout_btn6.png", dirPath .. "logout_btn5.png", dirPath .. "logout_btn_3.png"}
logout_suspend_icon = {dirPath .. "logout_suspend_icon.png"}
avatar_picture = {dirPath .. "avatar_picture.png"}
create_a_password = {dirPath .. "create_a_password.png"}
password_eye = {dirPath .. "password_eye.png"}

i_agree_btn = {dirPath .. "agree_btn.png"}
dont_allow = {dirPath .. "dont_allow_txt.png"}
space_short = {dirPath .. "space_short_en.png", dirPath .. "space_short_es.png", dirPath .. "space_short_vn.png"}
shift_keyboard_on = {dirPath .. "shift_keyboard_on.png"}
num_keyboard = {dirPath .. "num_keyboard.png"}
home_icon = {dirPath .. "home_icon.png"}
agree_facebook_term = {dirPath .. "agree_facebook_term.png", dirPath .. "agree_facebook_term2.png"}
contact_information = {dirPath .. "contact_information.png"}
contact_information_btn = {dirPath .. "contact_information_btn.png"}
add_new_contact_information = {dirPath .. "add_new_contact_information.png"}
add_mail = {dirPath .. "add_mail3.png"} 
add_email_address = {dirPath .. "add_email_address2.png", dirPath .. "enter_email_address.png"}
enter_confirm_code = {dirPath .. "enter_confirm_code.png"}
delete_mail = {dirPath .. "delete_mail.png"}
deleted_previous_mail = {dirPath .. "deleted_previous_mail2.png"}
deleted_previous_phone = {dirPath .. "deleted_previous_phone.png"}
added_email = {dirPath .. "added_email.png"}
contact_yagi = {dirPath .. "contact_yagi.png", dirPath .. "contact_yagi2.png", dirPath .. "contact_yagi3.png"}
contact_gmail = {dirPath .. "contact_gmail.png"}
contact_phone = {dirPath .. "contact_phone.png"}
contact_email_icon = {dirPath .. "contact_email_icon.png"}
contact_confirm_mail = {dirPath .. "contact_confirm_mail.png"}
contact_checkbox_account = {dirPath .. "contact_checkbox_account.png"}
contact_email_added = {dirPath .. "contact_email_added.png"}
contact_delete_phone = {dirPath .. "contact_delete_phone.png"}

add_a_phone_number = {dirPath .. "add_a_phone_number2.png"}
email_used_added = {dirPath .. "email_used_added.png"}
add_phone_number = {dirPath .. "add_phone_number2.png"}
add_phone_number_home = {dirPath .. "add_phone_number_home.png"}
join_facebook = {dirPath .. "join_facebook.png", dirPath .. "we_will_help.png"}
exist_account_in_mail = {dirPath .. "exist_account_in_mail2.png", dirPath .. "email_used_added.png"}
red_warning_icon = {dirPath .. "red_warning_icon.png"}
you_are_logged_in = {dirPath .. "you_are_logged_in.png"}
check_your_email = {dirPath .. "check_your_email6.png"}
confirm_human = {dirPath .. "icon_suspended.png", dirPath .. "giup_chung_toi_xac_nhan.png", 
    dirPath .. "confirm_human2.png", dirPath .. "human_confirm2.png", dirPath .. "dinh_chi_tai_khoan.png"} 
continue_code_mail = {dirPath .. "continue_code_mail3.png", dirPath .. "continue_code_mail.png", dirPath .. "next4.png"}
enter_code_2fa = {dirPath .. "enter_code_2fa2.png"}

leave_button = {dirPath .. "leave_button2.png"}
x_icon_search = {dirPath .. "x_icon_search.png"}
fb_logo_2 = {dirPath .. "fb_logo_2.png"}
xoainfo_logo = {dirPath .. "xoainfo_logo.png"}
xoainfo_reset_data = {dirPath .. "xoainfo_reset_data.png"}
xoainfo_info_fake = {dirPath .. "xoainfo_info_fake.png"}
logo_facebook_login = {dirPath .. "logo_facebook_login2.png", dirPath .. "logo_facebook_login.png"}
logo_fb_modern = {dirPath .. "logo_fb_modern.png"}
page_not_available_now = {dirPath .. "page_not_available_now.png", dirPath .. "page_not_available_now2.png", 
    dirPath .. "page_not_available_now3.png", dirPath .. "page_not_available_now4.png",
    dirPath .. "page_not_available_now5.png", dirPath .. "page_not_available_now9.png",
    dirPath .. "page_not_available_now9.png"}
did_not_get_code = {dirPath .. "did_not_get_code.png"}
input_confirm_code = {dirPath .. "input_confirm_code2.png"}
add_picture = {dirPath .. "add_picture.png"}
contact_icon = {dirPath .. "contact_icon.png"}
mail_did_not_receive_code = {dirPath .. "mail_did_not_receive_code.png"}
setting_up_for_fb = {dirPath .. "setting_up_for_fb.png"}
x_input_icon = {dirPath .. "x_input_icon.png"}
gender_options = {dirPath .. "gender_options.png"}
first_name_invalid = {dirPath .. "first_name_invalid.png"}
accept = {dirPath .. "accept1.png", dirPath .. "accept2.png", dirPath .. "accept3.png", dirPath .. "accept4.png"}
can_not_agree = {dirPath .. "can_not_agree3.png", dirPath .. "can_not_agree2.png"}
fb_logo_menu_left = {dirPath .. "fb_logo_menu_left.png"}

do_you_already_have_account = {dirPath .. "do_you_already_have_account2.png"}
register_by_phone = {dirPath .. "register_by_phone.png"}
enter_confirm_code_phone = {dirPath .. "gui_den_so.png", dirPath .. "enter_confirm_code_phone4.png", dirPath .. "enter_confirm_code_phone5.png"}
no_receive_code = {dirPath .. "did_not_get_code.png"}
confirm_via_email = {dirPath .. "confirm_via_email3.png"}
enter_an_email = {dirPath .. "enter_an_email3.png"}
mobile_or_email = {dirPath .. "mobile_or_email.png"}
login_password = {dirPath .. "login_password.png"}
login_button = {dirPath .. "login_button.png"}
what_app = {dirPath .. "what_app.png"}
check_notification_device = {dirPath .. "check_notification_device.png"}
confirm_via_change_email = {dirPath .. "confirm_via_change_email3.png"}
wrong_credentials = {dirPath .. "wrong_credentials.png"}
wifi_icon = {dirPath .. "wifi_icon.png"}
wifi_on = {dirPath .. "wifi_on.png", dirPath .. "wifi_on2.png"}
wifi_off = {dirPath .. "wifi_off.png"}
select_your_name = {dirPath .. "select_your_name2.png"}
airplane_icon = {dirPath .. "airplane_icon.png"}
airplane_off = {dirPath .. "airplane_off.png"}
airplane_on = {dirPath .. "airplane_on.png"}

welcome_to_profile = {dirPath .. "welcome_to_profile.png"}
lock_profile_page = {dirPath .. "lock_profile_page.png"}
select_position = {dirPath .. "select_position2.png", dirPath .. "select_position.png"}
current_city = {dirPath .. "current_city.png"}
add_hometown = {dirPath .. "add_hometown.png"}
add_company = {dirPath .. "add_company.png"}
add_relationship = {dirPath .. "add_relationship.png"}
add_coverphoto = {dirPath .. "add_coverphoto.png"}
add_moreinformation = {dirPath .. "add_moreinformation.png"}
high_school = {dirPath .. "high_school.png"}
add_school = {dirPath .. "add_school.png"}
add_university = {dirPath .. "add_university.png"}
view_profile_page = {dirPath .. "view_profile_page.png"}
edit_profile_page = {dirPath .. "edit_profile_page.png", dirPath .. "edit_profile_page2.png"}
bio_search_icon = {dirPath .. "bio_search_icon.png"}
remove_account_from_device = {dirPath .. "remove_account_from_device.png"}
go_xoa_account = {dirPath .. "go_xoa_account.png"}
go_xoa_account_blue = {dirPath .. "go_xoa_account_blue.png"}

friend_add_friend = {dirPath .. "friend_add_friend.png"}
friend_upload_contact = {dirPath .. "friend_upload_contact.png"}
friend_allow_contact = {dirPath .. "friend_allow_contact.png"}
friend_send_add_friend = {dirPath .. "friend_send_add_friend2.png", dirPath .. "friend_send_add_friend.png"}
btn_cai_dat = {dirPath .. "btn_cai_dat.png"}
contact_wait_confirm = {dirPath .. "contact_wait_confirm.png"}
contact_search_friend_page = {dirPath .. "contact_search_friend_page.png"}
profile_add_avatar = {dirPath .. "profile_add_avatar.png", dirPath .. "profile_add_avatar2.png"}
edit_profile_page_edit = {dirPath .. "edit_profile_page_edit.png"}
allow_access = {dirPath .. "allow_access.png"}
turn_on_contact_on = {dirPath .. "turn_on_contact_on.png"}
turn_on = {dirPath .. "turn_on.png"}
thu_vien_anh = {dirPath .. "thu_vien_anh.png"}
xem_truoc_anh_dai_dien = {dirPath .. "xem_truoc_anh_dai_dien.png"}
mo_trong_facebook = {dirPath .. "mo_trong_facebook.png"}
chon_anh_dai_dien = {dirPath .. "chon_anh_dai_dien.png"}
gio_ban_chua_dung_tinh_nang_nay = {dirPath .. "gio_ban_chua_dung_tinh_nang_nay.png"}
tiep_tuc_thiet_lap_profile = {dirPath .. "tiep_tuc_thiet_lap_profile.png"}
khong_the_thay_doi_avt = {dirPath .. "khong_the_thay_doi_avt.png"}
fb_logo_home = {dirPath .. "fb_logo_home.png"}
