
get_started = {currentPath() .. "/images_es/get_started.png"}
what_is_birthday = {currentPath() .. "/images_es/what_is_your_birthday.png"}
next = {currentPath() .. "/images_es/next.png"}
what_is_gender = {currentPath() .. "/images_es/what_is_your_gender.png"}
what_is_mobile_number = {currentPath() .. "/images_es/what_is_mobile_number.png"}
sign_up_with_email = {currentPath() .. "/images_es/sign_up_with_email.png"}
what_is_your_email = {currentPath() .. "/images_es/what_is_your_email.png"}
continue_creating_account = {currentPath() .. "/images_es/continue_creating_account.png"} 
save = {currentPath() .. "/images_es/save.png", currentPath() .. "/images_es/save2.png", currentPath() .. "/images_es/save5.png"}
save_your_login_info = {currentPath() .. "/images_es/save_your_login_info.png"}
enter_the_confirmation_code = {currentPath() .. "/images_es/enter_the_confirmation_code.png"}
profile_picture = {currentPath() .. "/images_es/profile_picture.png"}
turn_on_contact = {currentPath() .. "/images_es/turn_on_contact.png"}
skip = {currentPath() .. "/images_es/skip.png", currentPath() .. "/images_es/skip2.png", currentPath() .. "/images_es/skip3.png"}
not_now = {currentPath() .. "/images_es/not_now.png", currentPath() .. "/images_es/not_now2.png", currentPath() .. "/images_es/not_now3.png"}
no_friend = {currentPath() .. "/images_es/no_friend.png", currentPath() .. "/images_es/no_friend2.png"}
what_on_your_mind = {currentPath() .. "/images_es/what_on_your_mind.png"}

create_new_account = {currentPath() .. "/images_es/create_new_acc.png", currentPath() .. "/images_es/create_new_acc2.png", currentPath() .. "/images_es/create_new_acc3.png", currentPath() .. "/images_es/create_new_acc4.png", currentPath() .. "/images_es/create_new_acc4.png"}
create_new_account_blue = {currentPath() .. "/images_es/create_new_acc_blue.png"}
get_started = {currentPath() .. "/images_es/get_started2.png"}
what_name = {currentPath() .. "/images_es/what_name.png"}
already_have_account = {currentPath() .. "/images_es/already_have_account.png"}
setting_menu = {currentPath() .. "/images_es/setting_menu3.png", currentPath() .. "/images_es/setting_menu2.png", currentPath() .. "/images_es/setting_menu.png"}
setting_privacy = {currentPath() .. "/images_es/setting_privacy.png", currentPath() .. "/images_es/search_setting.png"}
see_more_account_center = {currentPath() .. "/images_es/see_more_account_center.png"}
account_center = {currentPath() .. "/images_es/account_center.png"}
personal_details_btn = {currentPath() .. "/images_es/personal_details_btn.png"}
personal_details_page = {currentPath() .. "/images_es/personal_details_page.png"}
identify_confirmation_btn = {currentPath() .. "/images_es/identify_confirmation_btn.png"}
confirm_your_identity = {currentPath() .. "/images_es/confirm_your_identity.png"}
reenter_password = {currentPath() .. "/images_es/reenter_password.png"}
help_protect_account = {currentPath() .. "/images_es/help_protect_account.png"}
instructions_for_setup = {currentPath() .. "/images_es/instructions_for_setup.png"}
copy_key = {currentPath() .. "/images_es/copy_key.png"}
two_FA_code = {currentPath() .. "/images_es/two_FA_code.png"}
two_factor_is_on = {currentPath() .. "/images_es/two_factor_is_on.png"}
logout_btn = {currentPath() .. "/images_es/logout_btn.png", currentPath() .. "/images_es/logout_red_btn.png", currentPath() .. "/images_es/logout_btn_3.png"}
logout_suspend_icon = {currentPath() .. "/images_es/logout_suspend_icon.png"}
avatar_picture = {currentPath() .. "/images_es/avatar_picture.png"}
create_a_password = {currentPath() .. "/images_es/create_a_password.png"}

i_agree_btn = {currentPath() .. "/images_es/agree.png"}
dont_allow = {currentPath() .. "/images_es/dont_allow_txt.png"}
space_short = {currentPath() .. "/images_es/space_short.png"}
shift_keyboard_on = {currentPath() .. "/images_es/shift_keyboard_on.png"}
num_keyboard = {currentPath() .. "/images_es/num_keyboard.png"}
home_icon = {currentPath() .. "/images_es/home_icon.png"}
agree_facebook_term = {currentPath() .. "/images_es/agree_facebook_term.png"}
protect_your_account = {currentPath() .. "/images_es/protect_your_account.png"}
-- contact_information = {currentPath() .. "/images_es/contact_information.png"}
-- add_mail = {currentPath() .. "/images_es/add_mail2.png"} 
-- add_email_address = {currentPath() .. "/images_es/add_email_address2.png", currentPath() .. "/images_es/enter_email_address.png"}
-- enter_confirm_code = {currentPath() .. "/images_es/enter_confirm_code.png"}
-- delete_mail = {currentPath() .. "/images_es/delete_mail.png"}
-- deleted_previous_mail = {currentPath() .. "/images_es/deleted_previous_mail.png"}
-- added_email = {currentPath() .. "/images_es/added_email.png"}
-- add_a_phone_number = {currentPath() .. "/images_es/add_a_phone_number.png"}
-- email_used_added = {currentPath() .. "/images_es/email_used_added.png"}
add_phone_number = {currentPath() .. "/images_es/add_phone_number.png"}
add_phone_number_home = {currentPath() .. "/images_es/add_phone_number_home.png"}
join_facebook = {currentPath() .. "/images_es/join_facebook.png", currentPath() .. "/images_es/we_will_help.png"}
exist_account_in_mail = {currentPath() .. "/images_es/exist_account_in_mail.png"}
you_are_logged_in = {currentPath() .. "/images_es/you_are_logged_in.png"}
check_your_email = {currentPath() .. "/images_es/check_your_email.png"}
confirm_human = {currentPath() .. "/images_es/icon_suspended.png", currentPath() .. "/images_es/human_confirm.png", currentPath() .. "/images_es/human_confirm2.png"} 
continue_code_mail = {currentPath() .. "/images_es/continue_code_mail.png"}
enter_code_2fa = {currentPath() .. "/images_es/enter_code_2fa.png"}

leave_button = {currentPath() .. "/images_es/leave_button.png"}
x_icon_search = {currentPath() .. "/images_es/x_icon_search.png"}
fb_logo_2 = {currentPath() .. "/images_es/fb_logo_2.png"}
to_sign_up_agree = {currentPath() .. "/images_es/to_sign_up_agree.png"}
xoainfo_logo = {currentPath() .. "/images_es/xoainfo_logo.png"}
xoainfo_reset_data = {currentPath() .. "/images_es/xoainfo_reset_data.png"}
xoainfo_info_fake = {currentPath() .. "/images_es/xoainfo_info_fake.png"}
logo_facebook_2 = {currentPath() .. "/images_es/logo_facebook_2.png"}
fb_logo_mode_new = {currentPath() .. "/images_es/fb_logo_mode_new.png"}
page_not_available_now = {currentPath() .. "/images_es/page_not_available_now5.png", currentPath() .. "/images_es/page_not_available_now.png", currentPath() .. "/images_es/page_not_available_now2.png", currentPath() .. "/images_es/page_not_available_now3.png", currentPath() .. "/images_es/page_not_available_now4.png"}
your_information_and_permission = {currentPath() .. "/images_es/your_information_and_permission.png"}
your_information_and_2 = {currentPath() .. "/images_es/your_information_and_2.png"}
did_not_get_code = {currentPath() .. "/images_es/did_not_get_code.png"}
add_picture = {currentPath() .. "/images_es/add_picture.png"}
input_confirm_code = {currentPath() .. "/images_es/input_confirm_code.png", currentPath() .. "/images_es/input_confirm_code2.png"}
