
get_started = {currentPath() .. "/images/get_started.png"}
what_is_your_name = {currentPath() .. "/images/what_is_your_name.png"}
what_is_birthday = {currentPath() .. "/images/what_is_your_birthday.png", currentPath() .. "/images/what_is_your_birthday2.png", currentPath() .. "/images/what_is_your_birthday11.png"}
next = {currentPath() .. "/images/next.png", currentPath() .. "/images/next2.png", currentPath() .. "/images/next3.png"}
what_is_gender = {currentPath() .. "/images/what_is_your_gender.png"}
what_is_mobile_number = {currentPath() .. "/images/what_is_your_phone2.png"}
sign_up_with_email = {currentPath() .. "/images/sign_up_with_email.png", currentPath() .. "/images/sign_up_with_mail2.png"}
what_is_your_email = {currentPath() .. "/images/what_is_your_email.png"}
continue_creating_account = {currentPath() .. "/images/continue_creating_account.png", currentPath() .. "/images/continue_create_account2.png"} 
password = {currentPath() .. "/images/password.png", currentPath() .. "/images/password2.png", currentPath() .. "/images/password3.png"}
save = {currentPath() .. "/images/save.png", currentPath() .. "/images/save2.png"}
save_your_login_info = {currentPath() .. "/images/save_login_info.png"}
agree_to = {currentPath() .. "/images/agree_to.png"}
i_agree = {currentPath() .. "/images/i_agree.png"}
enter_the_confirmation_code = {currentPath() .. "/images/enter_the_confirmation_code.png", currentPath() .. "/images/enter_the_confirmation_code2.png"}
get_the_code = {currentPath() .. "/images/get_the_code.png", currentPath() .. "/images/get_the_code2.png"}
confirm_by_email = {currentPath() .. "/images/confirm_by_email.png", currentPath() .. "/images/confirm_by_email2.png"}
input_email = {currentPath() .. "/images/input_email2.png"}
profile_picture = {currentPath() .. "/images/profile_picture.png", currentPath() .. "/images/profile_picture2.png"}
turn_on_contact = {currentPath() .. "/images/turn_on_contact.png"}
skip = {currentPath() .. "/images/skip.png", currentPath() .. "/images/skip2.png", currentPath() .. "/images/skip3.png"}
not_now = {currentPath() .. "/images/not_now4.png", currentPath() .. "/images/not_now2.png", currentPath() .. "/images/not_now3.png", currentPath() .. "/images/not_now.png", currentPath() .. "/images/not_now5.png", currentPath() .. "/images/not_now6.png"}
turn_on_contact2 = {currentPath() .. "/images/turn_on_contact2.png"}
no_friend = {currentPath() .. "/images/no_friend2.png", currentPath() .. "/images/no_friend.png"}
input_confirm_code = {currentPath() .. "/images/input_confirm_code.png"}
what_on_your_mind = {currentPath() .. "/images/what_on_your_mind.png"}
we_suspended = {currentPath() .. "/images/we_suspended.png"}

create_new_account = {currentPath() .. "/images/create_new_acc.png", currentPath() .. "/images/create_new_acc2.png"}
create_new_account_blue = {currentPath() .. "/images/create_new_acc_blue.png"}
get_started = {currentPath() .. "/images/get_started.png"}
what_name = {currentPath() .. "/images/what_name.png"}
already_have_account = {currentPath() .. "/images/already_have_account2.png"}
setting_menu = {currentPath() .. "/images/setting_menu2.png", currentPath() .. "/images/setting_menu.png"}
setting_privacy = {currentPath() .. "/images/setting_privacy.png", currentPath() .. "/images/search_setting.png"}
see_more_account_center = {currentPath() .. "/images/see_more_account_center.png"}
account_center = {currentPath() .. "/images/account_center.png"}
personal_details_btn = {currentPath() .. "/images/personal_details_btn.png"}
personal_details_page = {currentPath() .. "/images/personal_details_page.png"}
identify_confirmation_btn = {currentPath() .. "/images/identify_confirmation_btn.png"}
confirm_your_identity = {currentPath() .. "/images/confirm_your_identity.png"}
reenter_password = {currentPath() .. "/images/reenter_password.png"}
help_protect_account = {currentPath() .. "/images/help_protect_account.png"}
instructions_for_setup = {currentPath() .. "/images/instructions_for_setup.png"}
copy_key = {currentPath() .. "/images/copy_key.png"}
two_FA_code = {currentPath() .. "/images/two_FA_code.png"}
two_factor_is_on = {currentPath() .. "/images/two_factor_is_on.png"}
logout_btn = {currentPath() .. "/images/logout_btn.png", currentPath() .. "/images/logout_red_btn.png", currentPath() .. "/images/logout_btn_3.png"}
logout_suspend_icon = {currentPath() .. "/images/logout_suspend_icon.png"}
avatar_picture = {currentPath() .. "/images/avatar_picture.png"}
create_a_password = {currentPath() .. "/images/create_a_password.png"}

i_agree_btn = {currentPath() .. "/images/agree_btn.png"}
dont_allow = {currentPath() .. "/images/dont_allow_txt.png"}
space_short = {currentPath() .. "/images/space_short.png"}
shift_keyboard_on = {currentPath() .. "/images/shift_keyboard_on.png"}
num_keyboard = {currentPath() .. "/images/num_keyboard.png"}
home_icon = {currentPath() .. "/images/home_icon.png"}
agree_facebook_term = {currentPath() .. "/images/agree_facebook_term.png"}
protect_your_account = {currentPath() .. "/images/protect_your_account.png"}
contact_information = {currentPath() .. "/images/contact_information.png"}
add_mail = {currentPath() .. "/images/add_mail2.png"} 
add_email_address = {currentPath() .. "/images/add_email_address2.png", currentPath() .. "/images/enter_email_address.png"}
enter_confirm_code = {currentPath() .. "/images/enter_confirm_code.png"}
delete_mail = {currentPath() .. "/images/delete_mail.png"}
deleted_previous_mail = {currentPath() .. "/images/deleted_previous_mail.png"}
add_phone_number = {currentPath() .. "/images/add_phone_number.png"}
join_facebook = {currentPath() .. "/images/join_facebook.png", currentPath() .. "/images/we_will_help.png"}
exist_account_in_mail = {currentPath() .. "/images/exist_account_in_mail.png"}
you_are_logged_in = {currentPath() .. "/images/you_are_logged_in.png"}
check_your_email = {currentPath() .. "/images/check_your_email.png"}
confirm_human = {currentPath() .. "/images/icon_suspended.png", currentPath() .. "/images/confirm_human.png", currentPath() .. "/images/human_confirm.png"} 
continue_code_mail = {currentPath() .. "/images/continue_code_mail.png"}
enter_code_2fa = {currentPath() .. "/images/enter_code_2fa.png"}
added_email = {currentPath() .. "/images/added_email.png"}
add_a_phone_number = {currentPath() .. "/images/add_a_phone_number.png"}
leave_button = {currentPath() .. "/images/leave_button.png"}
email_used_added = {currentPath() .. "/images/email_used_added.png"}
do_you_already_have_account = {currentPath() .. "/images/do_you_already_have_account.png"}
x_icon_search = {currentPath() .. "/images/x_icon_search.png"}
fb_logo_2 = {currentPath() .. "/images/fb_logo_2.png"}
to_sign_up_agree = {currentPath() .. "/images/to_sign_up_agree.png"}

xoainfo_logo = {currentPath() .. "/images/xoainfo_logo.png"}
xoainfo_reset_data = {currentPath() .. "/images/xoainfo_reset_data.png"}
xoainfo_info_fake = {currentPath() .. "/images/xoainfo_info_fake.png"}
logo_facebook_2 = {currentPath() .. "/images/logo_facebook_2.png"}
