local dirPath = rootDir() .. "/Facebook/images_google/"

safari_icon = {dirPath .. "safari_icon.png"}
xoa_lich_su_du_lieu = {dirPath .. "xoa_lich_su_du_lieu.png"}
an_dia_chi_ip = {dirPath .. "an_dia_chi_ip.png"}
tim_trong_thu = {dirPath .. "tim_trong_thu.png"}
them_tai_khoan_khac = {dirPath .. "them_tai_khoan_khac.png", dirPath .. "them_tai_khoan_khac2.png"}
page_them_tai_khoan = {dirPath .. "page_them_tai_khoan.png", dirPath .. "page_them_tai_khoan2.png"}
setting_safari_page = {dirPath .. "setting_safari_page.png"}
safari_google_url = {dirPath .. "safari_google_url.png"}
dang_nhap = {dirPath .. "dang_nhap.png"}
tao_tai_khoan = {dirPath .. "tao_tai_khoan_text.png", dirPath .. "tao_tai_khoan_btn.png"}
danh_cho_ca_nhan = {dirPath .. "danh_cho_ca_nhan.png"}
nhap_ten_cua_ban = {dirPath .. "nhap_ten_cua_ban.png"}
first_name_input = {dirPath .. "first_name_input.png"}
last_name_input = {dirPath .. "last_name_input.png"}
tiep_theo = {dirPath .. "tiep_theo.png", dirPath .. "tiep_theo2.png"}
nhap_ngay_sinh = {dirPath .. "nhap_ngay_sinh.png"}
ngay_input = {dirPath .. "ngay_input.png", dirPath .. "ngay_input2.png"}
thang_input = {dirPath .. "thang_input.png", dirPath .. "thang_input2.png", dirPath .. "thang_input3.png"}
nam_input = {dirPath .. "nam_input.png", dirPath .. "nam_input2.png"}
gioitinh_nam_option = {dirPath .. "gioitinh_nam_option.png"}
gioitinh_nu_option = {dirPath .. "gioitinh_nu_option.png"}
gioi_tinh_input = {dirPath .. "gioi_tinh_input.png", dirPath .. "gioi_tinh_input2.png"}
thang_4 = {dirPath .. "thang_4.png", dirPath .. "thang_4_2.png"}
xong = {dirPath .. "xong.png"}

cach_ban_dang_nhap = {dirPath .. "cach_ban_dang_nhap.png"}
tao_mot_mat_khau = {dirPath .. "tao_mot_mat_khau.png"}
hien_mat_khau = {dirPath .. "hien_mat_khau.png"}
mat_khau_input = {dirPath .. "mat_khau_input.png", dirPath .. "mat_khau_input2.png"}
xac_nhan_input = {dirPath .. "xac_nhan_input.png"}
them_mail_khoi_phuc = {dirPath .. "them_mail_khoi_phuc.png"}
bo_qua = {dirPath .. "bo_qua.png"}
xin_chao = {dirPath .. "xin_chao.png", dirPath .. "xin_chao2.png"}
robot_confirm = {dirPath .. "robot_confirm.png"}

airplane_icon = {dirPath .. "airplane_icon.png"}
airplane_on = {dirPath .. "airplane_on2.png"}
airplane_off = {dirPath .. "airplane_off2.png"}

chon_dia_chi_email = {dirPath .. "chon_dia_chi_email.png"}
tao_dia_chi_gmail_rieng = {dirPath .. "tao_dia_chi_gmail_rieng.png", dirPath .. "tao_dia_chi_gmail_rieng2.png"}
gmail_welcome = {dirPath .. "gmail_welcome.png"}
quan_ly_tai_khoan = {dirPath .. "quan_ly_tai_khoan.png"}
google_option = {dirPath .. "google_option.png"}
tiep_tuc = {dirPath .. "tiep_tuc.png"}
xem_lai_thong_tin = {dirPath .. "xem_lai_thong_tin.png"}
quyen_rieng_tu = {dirPath .. "quyen_rieng_tu.png"}
toi_dong_y = {dirPath .. "toi_dong_y.png"}
ten_nguoi_dung = {dirPath .. "ten_nguoi_dung.png", dirPath .. "ten_nguoi_dung2.png"}
